services:
  api:
    container_name: habit_tracker_test_api
    environment:
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=habit_db_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: habit_tracker_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=habit_db_test
      - POSTGRES_PASSWORD=pass
volumes:
  test_db:
networks:
  default:
    name: habit_tracker_test
